use book_ez;

SELECT * FROM customer;

UPDATE book SET pubdate='March 01, 2004'WHERE book_id='3';





UPDATE book SET imageURLFull='/static/images/full/da-vinci-code.jpg'WHERE book_id='3';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-1.jpg'WHERE book_id='4';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-2.jpg'WHERE book_id='5';
UPDATE book SET imageURLFull='/static/images/full/angels-and-demons.jpg'WHERE book_id='6';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-5.jpg'WHERE book_id='7';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-6.jpg'WHERE book_id='8';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-7.jpg'WHERE book_id='9';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-3.jpg'WHERE book_id='10';
UPDATE book SET imageURLFull='/static/images/full/twilight.jpg'WHERE book_id='11';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-4.jpg'WHERE book_id='12';
UPDATE book SET imageURLFull='/static/images/full/deception-point.jpg'WHERE book_id='13';
UPDATE book SET imageURLFull='/static/images/full/new-moon.jpg'WHERE book_id='14';
UPDATE book SET imageURLFull='/static/images/full/the-lovely-bones.jpg'WHERE book_id='15';
UPDATE book SET imageURLFull='/static/images/full/digital-fortress.jpg'WHERE book_id='16';
UPDATE book SET imageURLFull='/static/images/full/curious-incident.jpg'WHERE book_id='17';
UPDATE book SET imageURLFull='/static/images/full/eclipse.jpg'WHERE book_id='18';
UPDATE book SET imageURLFull='/static/images/full/dragon-tattoo.jpg'WHERE book_id='19';
UPDATE book SET imageURLFull='/static/images/full/kite-runner.jpg'WHERE book_id='20';
UPDATE book SET imageURLFull='/static/images/full/time-travelers-wife.jpg'WHERE book_id='21';
UPDATE book SET imageURLFull='/static/images/full/world-according-clarkson.jpg'WHERE book_id='22';
UPDATE book SET imageURLFull='/static/images/full/attonement.jpg'WHERE book_id='23';
UPDATE book SET imageURLFull='/static/images/full/lost-symbol.jpg'WHERE book_id='24';
UPDATE book SET imageURLFull='/static/images/full/short-history.jpg'WHERE book_id='25';
UPDATE book SET imageURLFull='/static/images/full/breaking-dawn.jpg'WHERE book_id='26';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-4.jpg'WHERE book_id='27';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-7.jpg'WHERE book_id='28';
UPDATE book SET imageURLFull='/static/images/full/girl-who-played-with-fire.jpg'WHERE book_id='29';
UPDATE book SET imageURLFull='/static/images/full/child-called-it.jpg'WHERE book_id='30';
UPDATE book SET imageURLFull='/static/images/full/no-1-ladies-detective.jpg'WHERE book_id='31';
UPDATE book SET imageURLFull='/static/images/full/what-you-eat.jpg'WHERE book_id='32';
UPDATE book SET imageURLFull='/static/images/full/man-and-boy.jpg'WHERE book_id='33';
UPDATE book SET imageURLFull='/static/images/full/birdsong.jpg'WHERE book_id='34';
UPDATE book SET imageURLFull='/static/images/full/labryinth.jpg'WHERE book_id='35';
UPDATE book SET imageURLFull='/static/images/full/the-island.jpg'WHERE book_id='36';
UPDATE book SET imageURLFull='/static/images/full/life-of-pi.jpg'WHERE book_id='37';
UPDATE book SET imageURLFull='/static/images/full/doctor-atkins.jpg'WHERE book_id='38';
UPDATE book SET imageURLFull='/static/images/full/tales-of-beedle-bard.jpg'WHERE book_id='39';
UPDATE book SET imageURLFull='/static/images/full/captain-corellis-mandolin.jpg'WHERE book_id='40';
UPDATE book SET imageURLFull='/static/images/full/delias-cook.jpg'WHERE book_id='41';
UPDATE book SET imageURLFull='/static/images/full/gruffalo.jpg'WHERE book_id='42';
UPDATE book SET imageURLFull='/static/images/full/eats-shoots-leaves.jpg'WHERE book_id='43';
UPDATE book SET imageURLFull='/static/images/full/northern-lights.jpg'WHERE book_id='44';
UPDATE book SET imageURLFull='/static/images/full/interpretation-of-murder.jpg'WHERE book_id='45';
UPDATE book SET imageURLFull='/static/images/full/girl-who-kicked-hornets-nest.jpg'WHERE book_id='46';
UPDATE book SET imageURLFull='/static/images/full/bridget-jones-diary.jpg'WHERE book_id='47';
UPDATE book SET imageURLFull='/static/images/full/short-history-tractors.jpg'WHERE book_id='48';
UPDATE book SET imageURLFull='/static/images/full/alchemist.jpg'WHERE book_id='49';
UPDATE book SET imageURLFull='/static/images/full/notes-from-small-island.jpg'WHERE book_id='50';
UPDATE book SET imageURLFull='/static/images/full/boy-striped-pyjamas.jpg'WHERE book_id='51';
UPDATE book SET imageURLFull='/static/images/full/stupid-white-men.jpg'WHERE book_id='52';
UPDATE book SET imageURLFull='/static/images/full/30-minute-meals.jpg'WHERE book_id='53';
UPDATE book SET imageURLFull='/static/images/full/the-broker.jpg'WHERE book_id='54';
UPDATE book SET imageURLFull='/static/images/full/hungry-catipillar.jpg'WHERE book_id='55';
UPDATE book SET imageURLFull='/static/images/full/a-thousand-splendid-suns.jpg'WHERE book_id='56';
UPDATE book SET imageURLFull='/static/images/full/peter-kay.jpg'WHERE book_id='57';
UPDATE book SET imageURLFull='/static/images/full/interpretation-of-murder.jpg'WHERE book_id='58';
UPDATE book SET imageURLFull='/static/images/full/jamies-italy.jpg'WHERE book_id='59';
UPDATE book SET imageURLFull='/static/images/full/small-island.jpg'WHERE book_id='60';
UPDATE book SET imageURLFull='/static/images/full/memory-keepers-daughter.jpg'WHERE book_id='61';
UPDATE book SET imageURLFull='/static/images/full/billy.jpg'WHERE book_id='62';
UPDATE book SET imageURLFull='/static/images/full/house-at-riverton.jpg'WHERE book_id='63';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-5.jpg'WHERE book_id='64';
UPDATE book SET imageURLFull='/static/images/full/nigella-express.jpg'WHERE book_id='65';
UPDATE book SET imageURLFull='/static/images/full/memories-of-geisha.jpg'WHERE book_id='66';
UPDATE book SET imageURLFull='/static/images/full/delias-cook.jpg'WHERE book_id='67';
UPDATE book SET imageURLFull='/static/images/full/subtle-knife.jpg'WHERE book_id='68';
UPDATE book SET imageURLFull='/static/images/full/ministries-of-food.jpg'WHERE book_id='69';
UPDATE book SET imageURLFull='/static/images/full/guiness-world-record-2009.jpg'WHERE book_id='70';
UPDATE book SET imageURLFull='/static/images/full/why-don’t-penguins-feet-freeze.jpg'WHERE book_id='71';
UPDATE book SET imageURLFull='/static/images/full/jamie-at-home.jpg'WHERE book_id='72';
UPDATE book SET imageURLFull='/static/images/full/white-teeth.jpg'WHERE book_id='73';
UPDATE book SET imageURLFull='/static/images/full/devil-wears-prada.jpg'WHERE book_id='74';
UPDATE book SET imageURLFull='/static/images/full/at-my-mothers-knees.jpg'WHERE book_id='75';
UPDATE book SET imageURLFull='/static/images/full/no-time-for-goodbye.jpg'WHERE book_id='76';
UPDATE book SET imageURLFull='/static/images/full/soduku_book_instory.jpg'WHERE book_id='77';
UPDATE book SET imageURLFull='/static/images/full/chocolat.jpg'WHERE book_id='78';
UPDATE book SET imageURLFull='/static/images/full/return-of-the-naked-chef.jpg'WHERE book_id='79';
UPDATE book SET imageURLFull='/static/images/full/angelas-ashes.jpg'WHERE book_id='80';
UPDATE book SET imageURLFull='/static/images/full/original-miscellany.jpg'WHERE book_id='81';
UPDATE book SET imageURLFull='/static/images/full/dreams-from-my-father.jpg'WHERE book_id='82';
UPDATE book SET imageURLFull='/static/images/full/dangerous-book-for-boys.jpg'WHERE book_id='83';
UPDATE book SET imageURLFull='/static/images/full/kill-a-mocking-bird.jpg'WHERE book_id='84';
UPDATE book SET imageURLFull='/static/images/full/harry-potter-6.jpg'WHERE book_id='85';
UPDATE book SET imageURLFull='/static/images/full/summons.jpg'WHERE book_id='86';
UPDATE book SET imageURLFull='/static/images/full/lost-symbol.jpg'WHERE book_id='87';
UPDATE book SET imageURLFull='/static/images/full/catcher-in-the-rye.jpg'WHERE book_id='88';
UPDATE book SET imageURLFull='/static/images/full/i-can-make-you-thin.jpg'WHERE book_id='89';
UPDATE book SET imageURLFull='/static/images/full/happy-days-with-chef.jpg'WHERE book_id='90';
UPDATE book SET imageURLFull='/static/images/full/brick-lane.jpg'WHERE book_id='91';
UPDATE book SET imageURLFull='/static/images/full/undomestic-goddess.jpg'WHERE book_id='92';
UPDATE book SET imageURLFull='/static/images/full/book-theif.jpg'WHERE book_id='93';
UPDATE book SET imageURLFull='/static/images/full/undomestic-goddess.jpg'WHERE book_id='94';
UPDATE book SET imageURLFull='/static/images/full/got-soul.jpg'WHERE book_id='95';
UPDATE book SET imageURLFull='/static/images/full/sharon-osbourne.jpg'WHERE book_id='96';
UPDATE book SET imageURLFull='/static/images/full/guiness-2010.jpg'WHERE book_id='97';
UPDATE book SET imageURLFull='/static/images/full/amber-spyglass.jpg'WHERE book_id='98';
UPDATE book SET imageURLFull='/static/images/full/keep-secret.jpg'WHERE book_id='99';
UPDATE book SET imageURLFull='/static/images/full/down-under.jpg'WHERE book_id='100';
UPDATE book SET imageURLFull='/static/images/full/spot-of-brother.jpg'WHERE book_id='101';
UPDATE book SET imageURLFull='/static/images/full/dawn-french.jpg'WHERE book_id='102';

